package com.codemastersTournament.PersonnelManagerBot.utils.enums;

public enum ButtonCallBackQuery {
    ADD_EMPLOYEE, DELETE_EMPLOYEE, OPEN_CARD_EMPLOYEE,SEARCH_EMPLOYEE_BY_PROJECT_LIST,SEARCH_EMPLOYEE_BY_POSITION_LIST,
    SEARCH_EMPLOYEE_BY_FIO,SEARCH_EMPLOYEE_BY_POSITION,SEARCH_EMPLOYEE_BY_PROJECT,SEARCH_EMPLOYEE_BY_DATE,
    VIEW_ALL, BACK, CHANGE_NAME, CHANGE_PATRONYMIC,CHANGE_LAST_NAME,CHANGE_POSITION,CHANGE_PROJECT,CHANGE_AVATAR
}
