package com.codemastersTournament.PersonnelManagerBot.utils.enums;

public enum ButtonCallBackQuery {
    ADD_EMPLOYEE, DELETE_EMPLOYEE, OPEN_CARD_EMPLOYEE, SEARCH_EMPLOYEE, BACK,
    CHANGE_NAME, CHANGE_PATRONYMIC,CHANGE_LAST_NAME,CHANGE_POSITION,CHANGE_PROJECT,CHANGE_AVATAR
}
